### ISSUE TITLE
window.foxitAssetURL is undefined for me

### ISSUE THREAD

**Issue by r3dapple** [jyooru/pearson-pdf#180] opened 2022-10-03 18:19 UTC
Title says it all
![image](https://user-images.githubusercontent.com/35780521/193649886-8157b392-f71c-48d4-b03d-d4cc1539cc42.png)

**Comment by jyooru** [comment] 2022-10-04 04:54
Duplicate of 175

**Closed by jyooru** 2022-10-04 04:54 UTC
