### ISSUE TITLE
Book download error

### ISSUE THREAD

**Issue by MicheleSottocasa** [jyooru/pearson-pdf#190] opened 2022-11-14 08:47 UTC
When I try to download a book, I'll get this error
```
Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\Scripts\pearson-pdf.exe\__main__.py", line 7, in <module>
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pearson_pdf\__main__.py", line 21, in main
    combine_pages(download_pages(parsed_args.book), parsed_args.save_path)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pearson_pdf\__init__.py", line 25, in download_pages
    raise PageDownloadError(f"No pages could be downloaded for {book_url}.")
pearson_pdf.PageDownloadError: No pages could be downloaded for https://etext-content.gls.pearson-intl.com/eplayer/pdfassets/prod1/145001/b21f1e4d-8e5e-4c2a-b603-073e13326802.
```

The command I used is:
` pearson-pdf 'https://etext-content.gls.pearson-intl.com/eplayer/pdfassets/prod1/145001/b21f1e4d-8e5e-4c2a-b603-073e13326802' out.pdf`
I have already tried to remove the quotes from the url, but nothing changes
I have also tried to download another book, but I have the same error

**Comment by jyooru** [comment] 2022-11-15 11:12
If you open that URL in an incognito tab (so you're logged out) you will get an Access Denied error, so this script cannot download it. I'm not sure why this doesn't happen with the books I have - Pearson seems to have a bunch of different ways to let people access their books. This domain is quite similar to a report I've received before, so please [see this comment](https://github.com/jyooru/pearson-pdf/issues/48#issuecomment-1028473785).

**Comment by jyooru** [comment] 2022-11-15 11:13
Duplicate of #48

**Closed by jyooru** 2022-11-15 11:13 UTC
